version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env

    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14.6-alpine
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
